import { defineStore } from "pinia";
import { ref, computed } from "vue";
import type {
  PersonaRecord,
  PersonaCreatePayload,
  PersonaUpdatePayload,
  PersonaDistillPayload,
  PersonaCorrectionPayload,
  PersonaVersionRecord,
  PersonaCorrectionRecord,
} from "../types";
import * as api from "../api";
import { useVoiceConfigStore } from "./voiceConfig";
import { resolveTtsSettings } from "../lib/ttsSettings";

export const usePersonaStore = defineStore("persona", () => {
  const personas = ref<PersonaRecord[]>([]);
  const activePersona = ref<PersonaRecord | null>(null);
  const loading = ref(false);
  const distilling = ref(false);

  // Dialog visibilities
  const workshopDialogOpen = ref(false);
  const distillWizardOpen = ref(false);
  const correctionDialogOpen = ref(false);
  const justAutoGenerated = ref(false);

  // Detail sub-states
  const selectedPersonaForEdit = ref<PersonaRecord | null>(null);
  const versions = ref<PersonaVersionRecord[]>([]);
  const corrections = ref<PersonaCorrectionRecord[]>([]);

  const activePersonaName = computed(() => activePersona.value?.name || "微光");
  const activeCompiledPrompt = computed(() => activePersona.value?.compiled_prompt || "");
  const activeVoiceStyle = computed(() => activePersona.value?.persona?.layer2_expression_dna?.voice_style || {});
  const activeTtsSettings = computed(() => resolveTtsSettings(activeVoiceStyle.value));
  const activeTtsInstruction = computed(() => activeTtsSettings.value.instruction);
  const activeTtsSampleRate = computed(() => activeTtsSettings.value.sample_rate);
  const activeTtsRate = computed(() => activeTtsSettings.value.rate);

  async function loadPersonas(): Promise<PersonaRecord[]> {
    loading.value = true;
    try {
      const list = await api.fetchPersonas();
      personas.value = list;
      const active = list.find((p) => p.is_active) || list[0] || null;
      activePersona.value = active;
      if (active) {
        syncToVoiceConfig(active);
      }
      return list;
    } finally {
      loading.value = false;
    }
  }

  function syncToVoiceConfig(persona: PersonaRecord) {
    const voiceStore = useVoiceConfigStore();
    if (persona.compiled_prompt) {
      voiceStore.characterManifest = persona.compiled_prompt;
    }
    if (persona.voice_id) {
      voiceStore.speaker = persona.voice_id;
    }
  }

  async function switchPersona(personaId: string): Promise<PersonaRecord> {
    loading.value = true;
    try {
      const activated = await api.activatePersona(personaId);
      personas.value = personas.value.map((p) => ({
        ...p,
        is_active: p.id === personaId,
      }));
      activePersona.value = activated;
      syncToVoiceConfig(activated);
      return activated;
    } finally {
      loading.value = false;
    }
  }

  async function createNewPersona(payload: PersonaCreatePayload): Promise<PersonaRecord> {
    loading.value = true;
    try {
      const created = await api.createPersona(payload);
      await loadPersonas();
      if (payload.is_active) {
        activePersona.value = created;
        syncToVoiceConfig(created);
      }
      return created;
    } finally {
      loading.value = false;
    }
  }

  async function savePersona(
    personaId: string,
    payload: PersonaUpdatePayload,
  ): Promise<PersonaRecord> {
    loading.value = true;
    try {
      const updated = await api.updatePersona(personaId, payload);
      personas.value = personas.value.map((p) => (p.id === personaId ? updated : p));
      if (activePersona.value?.id === personaId) {
        activePersona.value = updated;
        syncToVoiceConfig(updated);
      }
      if (selectedPersonaForEdit.value?.id === personaId) {
        selectedPersonaForEdit.value = updated;
      }
      return updated;
    } finally {
      loading.value = false;
    }
  }

  async function removePersona(personaId: string): Promise<void> {
    loading.value = true;
    try {
      await api.deletePersona(personaId);
      await loadPersonas();
    } finally {
      loading.value = false;
    }
  }

  async function triggerDistill(
    personaId: string,
    payload: PersonaDistillPayload,
  ): Promise<PersonaRecord> {
    distilling.value = true;
    try {
      const res = await api.distillPersona(personaId, payload);
      await loadPersonas();
      if (selectedPersonaForEdit.value?.id === personaId) {
        selectedPersonaForEdit.value = res.persona;
      }
      if (activePersona.value?.id === personaId) {
        activePersona.value = res.persona;
        syncToVoiceConfig(res.persona);
      }
      return res.persona;
    } finally {
      distilling.value = false;
    }
  }

  async function autoDistillFromImport(importId: number, name?: string): Promise<PersonaRecord> {
    distilling.value = true;
    try {
      const res = await api.distillPersonaFromImport({ import_id: importId, name });
      await loadPersonas();
      activePersona.value = res.persona;
      selectedPersonaForEdit.value = res.persona;
      syncToVoiceConfig(res.persona);
      justAutoGenerated.value = true;
      workshopDialogOpen.value = true;
      return res.persona;
    } finally {
      distilling.value = false;
    }
  }

  async function autoApplyImport(importId:number):Promise<PersonaRecord> {
    if (!activePersona.value) throw new Error('当前角色尚未就绪');
    distilling.value=true;
    try {
      const res=await api.distillPersonaFromImport({import_id:importId,persona_id:activePersona.value.id,name:activePersona.value.name});
      await loadPersonas();
      return res.persona;
    } finally { distilling.value=false; }
  }

  async function loadVersions(personaId: string): Promise<PersonaVersionRecord[]> {
    try {
      const list = await api.fetchPersonaVersions(personaId);
      versions.value = list;
      return list;
    } catch {
      versions.value = [];
      return [];
    }
  }

  async function rollback(personaId: string, versionId: number): Promise<PersonaRecord> {
    loading.value = true;
    try {
      const rolled = await api.rollbackPersonaVersion(personaId, versionId);
      await loadPersonas();
      await loadVersions(personaId);
      if (selectedPersonaForEdit.value?.id === personaId) {
        selectedPersonaForEdit.value = rolled;
      }
      if (activePersona.value?.id === personaId) {
        activePersona.value = rolled;
        syncToVoiceConfig(rolled);
      }
      return rolled;
    } finally {
      loading.value = false;
    }
  }

  async function loadCorrections(personaId: string): Promise<PersonaCorrectionRecord[]> {
    try {
      const list = await api.fetchPersonaCorrections(personaId);
      corrections.value = list;
      return list;
    } catch {
      corrections.value = [];
      return [];
    }
  }

  async function submitCorrection(
    personaId: string,
    payload: PersonaCorrectionPayload,
  ): Promise<PersonaCorrectionRecord> {
    loading.value = true;
    try {
      const rec = await api.addPersonaCorrection(personaId, payload);
      await loadCorrections(personaId);
      await loadPersonas();
      return rec;
    } finally {
      loading.value = false;
    }
  }

  async function removeCorrection(personaId: string, correctionId: number): Promise<void> {
    try {
      await api.deletePersonaCorrection(personaId, correctionId);
      await loadCorrections(personaId);
      await loadPersonas();
    } catch (err) {
      console.error("Failed to delete correction:", err);
    }
  }

  async function toggleCorrectionStatus(
    personaId: string,
    correctionId: number,
    isActive: boolean,
  ): Promise<void> {
    try {
      await api.togglePersonaCorrection(personaId, correctionId, isActive);
      await loadCorrections(personaId);
      await loadPersonas();
    } catch (err) {
      console.error("Failed to toggle correction:", err);
    }
  }

  function openWorkshop(persona?: PersonaRecord) {
    if (persona) {
      selectedPersonaForEdit.value = persona;
    } else if (activePersona.value) {
      selectedPersonaForEdit.value = activePersona.value;
    }
    workshopDialogOpen.value = true;
  }

  function closeWorkshop() {
    workshopDialogOpen.value = false;
  }

  function openDistillWizard(persona?: PersonaRecord) {
    if (persona) {
      selectedPersonaForEdit.value = persona;
    }
    distillWizardOpen.value = true;
  }

  function closeDistillWizard() {
    distillWizardOpen.value = false;
  }

  function openCorrectionDialog() {
    correctionDialogOpen.value = true;
  }

  function closeCorrectionDialog() {
    correctionDialogOpen.value = false;
  }

  return {
    personas,
    activePersona,
    loading,
    distilling,
    workshopDialogOpen,
    distillWizardOpen,
    correctionDialogOpen,
    justAutoGenerated,
    selectedPersonaForEdit,
    versions,
    corrections,
    activePersonaName,
    activeCompiledPrompt,
    activeTtsInstruction,
    activeTtsSampleRate,
    activeTtsRate,
    loadPersonas,
    switchPersona,
    createNewPersona,
    savePersona,
    removePersona,
    triggerDistill,
    autoDistillFromImport,
    autoApplyImport,
    loadVersions,
    rollback,
    loadCorrections,
    submitCorrection,
    removeCorrection,
    toggleCorrectionStatus,
    openWorkshop,
    closeWorkshop,
    openDistillWizard,
    closeDistillWizard,
    openCorrectionDialog,
    closeCorrectionDialog,
  };
});
